Specify path argument to isort to fix build error
Since isort 5.2.2, specifying command line options to isort without
specifying a path argument leads to the following error:

    Error: arguments passed in without any paths or content.

See PyCQA/isort@39adcee for more details.

This leads to a linting error while building with Python 3.6 or later.
Fix this issue by specifying the current directory as the path
argument to isort.

Nothing to do: no files or paths have have been passed in!